### ISSUE TITLE
Pergunta: Adicionar elementos na página

### ISSUE THREAD

**Issue by zeluizr** [vtex-apps/checkout-ui-custom#45]
Olá,

Para adicionar elementos na página como por exemplo um checkbox para aceitar Termos e Condições por exemplo.

Isso segue sendo igual que a versão do Checkout original onde eu adiciono via JS?

Muito obrigado!

Abs.,

José Luiz Rodrigues
commente.me

**Comment by lucvysk** [comment]
Adiciona via js, na aba de "Custom JS". Não esquece de ativar ela embaixo!
