### ISSUE TITLE
Double Address Form if adding new addresses.

### ISSUE THREAD

**Issue by DrewNF** [vtex-apps/checkout-ui-custom#60]
To replicate it you can just go to the checkout with myemail: andrea.ferri@vtex.com.br and try to add an address then as you will see the double form is showing:

<img width="614" alt="Screenshot 2021-05-26 at 16 24 36" src="https://user-images.githubusercontent.com/2854222/119840863-a17d0980-bf05-11eb-8a8d-6e30223e9e15.png">

Let me know if you have any doubt!

Bests

Andrea

**Comment by DrewNF** [comment]
Here a video of the problem:

https://user-images.githubusercontent.com/2854222/122018087-d244b600-cdc2-11eb-8648-1bf7741da82b.mov

Please let me know if you have any doubt!

Bests

Andrea

**Comment by lucvysk** [comment]
Hi @DrewNF , can you try to replicate this with the checkout without customizations, pls? https://vysk--arcaplanetqa.myvtex.com/checkout/cart/add/?sku=5505&qty=1&seller=1&sc=1

**Comment by DrewNF** [comment]
Hi @lucvysk, 

I cannot see it happening, could you identify which personalization is generating the problem?
I will let the agency know, but this will take a lot of time for them to properly debug and understand which one is causing it.

So different from last time, this is not from our component? You can confirm, right?

Bests

Andrea

**Comment by DrewNF** [comment]
@lucvysk the client says we have this problem since the release of the manual address

**Comment by lucvysk** [comment]
As we talked internally, the error was caused due the custom js added to the store.
