### ISSUE TITLE
Different markup for the items shown when clicking on the "Mostrar más itenes" button

### ISSUE THREAD

**Issue by sconverti-lyr** [vtex-apps/checkout-ui-custom#69]
The "product-item" rows initially have a child wrapper with a class "v-custom-product-item-wrap", but when the cart has a lot of products and you click on the "Mostrar más itenes", the new rows shown don't have that wrapper, causing inconsistencies when styling the parent element of the group of cells of every row.

![Screenshot from 2021-09-09 10-44-57](https://user-images.githubusercontent.com/72885897/132697404-339eeb68-2346-4e70-ac51-a828471fa3f5.png)

**Comment by lucvysk** [comment]
Fixed in this PR: https://github.com/vtex-apps/checkout-ui-custom/pull/70
